// 3WM SONIK — Master 808 & Drum Loop Library & Groove Patterns (v1.0)
import { SequencerLoopPreset, StepSequencerChannel } from '../types';

export const SEQUENCER_LOOP_LIBRARY: SequencerLoopPreset[] = [
  // --------------------------------------------------------------------------
  // 1. TRAP: ATLANTA MIDNIGHT (140 BPM, F Minor)
  // --------------------------------------------------------------------------
  {
    id: 'loop-atlanta-night',
    name: 'Atlanta Midnight 140',
    category: 'TRAP',
    bpm: 140,
    key: 'F Minor',
    description:
      'Metro-style heavy rolling 808 bassline with octave jump (F1 -> F2 -> D#1), 4x rolling hats, and crisp claps.',
    eight08PresetId: '808-sub-king',
    channels: [
      {
        id: 'ch-808-atlanta',
        name: 'SONIK 808 Sub (F1)',
        sampleKey: 'sonik_808',
        pitch: 41, // F1
        volume: 0.95,
        pan: 0,
        muted: false,
        solo: false,
        is808Channel: true,
        eight08Params: {
          mode: 'DEEP',
          waveform: 'sine',
          glideTime: 65,
          punchAttack: 0.85,
          decay: 1.8,
          drive: 0.3,
          subBoost: 5.0,
          legato: true,
        },
        steps: [
          {
            enabled: true,
            pitch: 41,
            noteName: 'F1',
            velocity: 120,
            probability: 1,
            offset: 0,
            accent: true,
          },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          {
            enabled: true,
            pitch: 41,
            noteName: 'F1',
            velocity: 105,
            probability: 1,
            offset: 0,
            accent: false,
          },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          {
            enabled: true,
            pitch: 53,
            noteName: 'F2',
            velocity: 115,
            probability: 1,
            offset: 0,
            accent: true,
            slide: true,
          },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          {
            enabled: true,
            pitch: 41,
            noteName: 'F1',
            velocity: 110,
            probability: 1,
            offset: 0,
            accent: false,
          },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          {
            enabled: true,
            pitch: 39,
            noteName: 'D#1',
            velocity: 112,
            probability: 1,
            offset: 0,
            accent: false,
          },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          {
            enabled: true,
            pitch: 37,
            noteName: 'C#1',
            velocity: 108,
            probability: 1,
            offset: 0,
            accent: false,
            slide: true,
          },
          {
            enabled: true,
            pitch: 41,
            noteName: 'F1',
            velocity: 95,
            probability: 1,
            offset: 0,
            accent: false,
          },
        ],
      },
      {
        id: 'ch-kick-atlanta',
        name: 'Hard Punch Kick',
        sampleKey: 'kick',
        pitch: 36,
        volume: 0.92,
        pan: 0,
        muted: false,
        solo: false,
        steps: [
          { enabled: true, velocity: 120, probability: 1, offset: 0, accent: true },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 105, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 115, probability: 1, offset: 0, accent: true },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 110, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
        ],
      },
      {
        id: 'ch-clap-atlanta',
        name: 'Trap Crisp Clap',
        sampleKey: 'clap',
        pitch: 39,
        volume: 0.88,
        pan: 0,
        muted: false,
        solo: false,
        steps: [
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 115, probability: 1, offset: 0, accent: true },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 115, probability: 1, offset: 0, accent: true },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
        ],
      },
      {
        id: 'ch-hihat-atlanta',
        name: 'Rolling Trap Hats',
        sampleKey: 'closed_hat',
        pitch: 42,
        volume: 0.78,
        pan: 0.15,
        muted: false,
        solo: false,
        steps: [
          { enabled: true, velocity: 95, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 75, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 90, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 80, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 95, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 75, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 110, probability: 1, offset: 0, accent: true, ratchet: 4 },
          { enabled: true, velocity: 90, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 95, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 75, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 90, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 80, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 95, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 85, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 115, probability: 1, offset: 0, accent: true, ratchet: 4 },
          { enabled: true, velocity: 95, probability: 1, offset: 0, accent: false },
        ],
      },
      {
        id: 'ch-openhat-atlanta',
        name: 'Open Hat Sizzle',
        sampleKey: 'open_hat',
        pitch: 46,
        volume: 0.7,
        pan: -0.2,
        muted: false,
        solo: false,
        steps: [
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 90, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 90, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
        ],
      },
    ],
  },

  // --------------------------------------------------------------------------
  // 2. DRILL: LONDON DRILL SLIDES (142 BPM, D Minor)
  // --------------------------------------------------------------------------
  {
    id: 'loop-london-drill',
    name: 'London Drill Slide 142',
    category: 'DRILL',
    bpm: 142,
    key: 'D Minor',
    description:
      'UK Drill sliding 808 notes (D1 -> D2 high slide -> F1 -> A#0) with stuttering triplet hi-hats and metallic rim.',
    eight08PresetId: '808-uk-drill-slide',
    channels: [
      {
        id: 'ch-808-drill',
        name: 'SONIK 808 Drill Beast',
        sampleKey: 'sonik_808',
        pitch: 38, // D1
        volume: 0.96,
        pan: 0,
        muted: false,
        solo: false,
        is808Channel: true,
        eight08Params: {
          mode: 'DISTORTED',
          waveform: 'sawtooth',
          glideTime: 140,
          punchAttack: 0.92,
          decay: 2.0,
          drive: 0.75,
          subBoost: 6.0,
          legato: true,
        },
        steps: [
          {
            enabled: true,
            pitch: 38,
            noteName: 'D1',
            velocity: 120,
            probability: 1,
            offset: 0,
            accent: true,
          },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          {
            enabled: true,
            pitch: 50,
            noteName: 'D2',
            velocity: 110,
            probability: 1,
            offset: 0,
            accent: true,
            slide: true,
          },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          {
            enabled: true,
            pitch: 41,
            noteName: 'F1',
            velocity: 115,
            probability: 1,
            offset: 0,
            accent: false,
          },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          {
            enabled: true,
            pitch: 38,
            noteName: 'D1',
            velocity: 105,
            probability: 1,
            offset: 0,
            accent: false,
          },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          {
            enabled: true,
            pitch: 46,
            noteName: 'A#1',
            velocity: 118,
            probability: 1,
            offset: 0,
            accent: true,
            slide: true,
          },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          {
            enabled: true,
            pitch: 34,
            noteName: 'A#0',
            velocity: 112,
            probability: 1,
            offset: 0,
            accent: false,
          },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
        ],
      },
      {
        id: 'ch-kick-drill',
        name: 'Drill Sub Kick',
        sampleKey: 'kick',
        pitch: 36,
        volume: 0.92,
        pan: 0,
        muted: false,
        solo: false,
        steps: [
          { enabled: true, velocity: 120, probability: 1, offset: 0, accent: true },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 110, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 115, probability: 1, offset: 0, accent: true },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
        ],
      },
      {
        id: 'ch-snare-drill',
        name: 'Drill Snare / Rim',
        sampleKey: 'snare',
        pitch: 38,
        volume: 0.9,
        pan: 0,
        muted: false,
        solo: false,
        steps: [
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 120, probability: 1, offset: 0, accent: true },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 105, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
        ],
      },
      {
        id: 'ch-hihat-drill',
        name: 'Drill Triplet Hats',
        sampleKey: 'closed_hat',
        pitch: 42,
        volume: 0.8,
        pan: -0.15,
        muted: false,
        solo: false,
        steps: [
          { enabled: true, velocity: 90, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 85, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 110, probability: 1, offset: 0, accent: true, ratchet: 3 },
          { enabled: true, velocity: 90, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 85, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 115, probability: 1, offset: 0, accent: true, ratchet: 6 },
          { enabled: true, velocity: 95, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 85, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 90, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 110, probability: 1, offset: 0, accent: true, ratchet: 3 },
          { enabled: true, velocity: 85, probability: 1, offset: 0, accent: false },
        ],
      },
    ],
  },

  // --------------------------------------------------------------------------
  // 3. AFROFUSION: LAGOS 3-STEP BOUNCE (106 BPM, F# Minor)
  // --------------------------------------------------------------------------
  {
    id: 'loop-lagos-afrofusion',
    name: 'Lagos 3-Step Afro Bounce 106',
    category: 'AFROFUSION',
    bpm: 106,
    key: 'F# Minor',
    description:
      'Syncopated Lagos Afrobeat pocket blending punchy 808 sub, Kalakuta kicks, shekere, and talking drum accents.',
    eight08PresetId: '808-lagos-bounce',
    channels: [
      {
        id: 'ch-808-lagos',
        name: 'SONIK Lagos Log 808',
        sampleKey: 'sonik_808',
        pitch: 42, // F#1
        volume: 0.94,
        pan: 0,
        muted: false,
        solo: false,
        is808Channel: true,
        eight08Params: {
          mode: 'PUNCH',
          waveform: 'triangle',
          glideTime: 45,
          punchAttack: 1.0,
          decay: 1.3,
          drive: 0.35,
          subBoost: 5.5,
          legato: false,
        },
        steps: [
          {
            enabled: true,
            pitch: 42,
            noteName: 'F#1',
            velocity: 118,
            probability: 1,
            offset: 0,
            accent: true,
          },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          {
            enabled: true,
            pitch: 45,
            noteName: 'A1',
            velocity: 105,
            probability: 1,
            offset: 0,
            accent: false,
          },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          {
            enabled: true,
            pitch: 47,
            noteName: 'B1',
            velocity: 112,
            probability: 1,
            offset: 0,
            accent: true,
          },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          {
            enabled: true,
            pitch: 40,
            noteName: 'E1',
            velocity: 115,
            probability: 1,
            offset: 0,
            accent: true,
          },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          {
            enabled: true,
            pitch: 42,
            noteName: 'F#1',
            velocity: 110,
            probability: 1,
            offset: 0,
            accent: false,
          },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          {
            enabled: true,
            pitch: 49,
            noteName: 'C#2',
            velocity: 105,
            probability: 1,
            offset: 0,
            accent: false,
            slide: true,
          },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
        ],
      },
      {
        id: 'ch-kick-lagos',
        name: 'Kalakuta Kick',
        sampleKey: 'kick',
        pitch: 36,
        volume: 0.94,
        pan: 0,
        muted: false,
        solo: false,
        steps: [
          { enabled: true, velocity: 120, probability: 1, offset: 0, accent: true },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 105, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 115, probability: 1, offset: 0, accent: true },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 108, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 110, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
        ],
      },
      {
        id: 'ch-snare-lagos',
        name: 'Lagos Rimshot',
        sampleKey: 'snare',
        pitch: 38,
        volume: 0.88,
        pan: -0.1,
        muted: false,
        solo: false,
        steps: [
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 112, probability: 1, offset: 0, accent: true },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 115, probability: 1, offset: 0, accent: true },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
        ],
      },
      {
        id: 'ch-shaker-lagos',
        name: 'Shekere 16th Shuffle',
        sampleKey: 'shaker',
        pitch: 42,
        volume: 0.76,
        pan: 0.25,
        muted: false,
        solo: false,
        steps: [
          { enabled: true, velocity: 95, probability: 1, offset: 0, accent: true },
          { enabled: true, velocity: 65, probability: 1, offset: 0.1, accent: false },
          { enabled: true, velocity: 85, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 60, probability: 1, offset: 0.1, accent: false },
          { enabled: true, velocity: 90, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 70, probability: 1, offset: 0.1, accent: false },
          { enabled: true, velocity: 85, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 65, probability: 1, offset: 0.1, accent: false },
          { enabled: true, velocity: 95, probability: 1, offset: 0, accent: true },
          { enabled: true, velocity: 65, probability: 1, offset: 0.1, accent: false },
          { enabled: true, velocity: 85, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 60, probability: 1, offset: 0.1, accent: false },
          { enabled: true, velocity: 90, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 70, probability: 1, offset: 0.1, accent: false },
          { enabled: true, velocity: 90, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 65, probability: 1, offset: 0.1, accent: false },
        ],
      },
      {
        id: 'ch-conga-lagos',
        name: 'Talking Drum & Conga',
        sampleKey: 'conga',
        pitch: 45,
        volume: 0.82,
        pan: -0.25,
        muted: false,
        solo: false,
        steps: [
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 95, probability: 0.95, offset: 0.12, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 90, probability: 0.9, offset: 0.15, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 95, probability: 0.95, offset: 0.1, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 92, probability: 0.9, offset: 0.15, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
        ],
      },
    ],
  },

  // --------------------------------------------------------------------------
  // 4. AMAPIANO: SOWETO LOG-808 (113 BPM, A Minor)
  // --------------------------------------------------------------------------
  {
    id: 'loop-amapiano-log',
    name: 'Soweto Log-808 113',
    category: 'AMAPIANO',
    bpm: 113,
    key: 'A Minor',
    description:
      'Johannesburg log drum bounce blended with low 808 resonant sub drops and offbeat shakers.',
    eight08PresetId: '808-amapiano-rumble',
    channels: [
      {
        id: 'ch-808-amapiano',
        name: 'SONIK Soweto Log 808',
        sampleKey: 'sonik_808',
        pitch: 45, // A1
        volume: 0.96,
        pan: 0,
        muted: false,
        solo: false,
        is808Channel: true,
        eight08Params: {
          mode: 'SUB',
          waveform: 'sine',
          glideTime: 55,
          punchAttack: 0.9,
          decay: 1.6,
          drive: 0.42,
          subBoost: 7.0,
          legato: true,
        },
        steps: [
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          {
            enabled: true,
            pitch: 45,
            noteName: 'A1',
            velocity: 120,
            probability: 1,
            offset: 0,
            accent: true,
          },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          {
            enabled: true,
            pitch: 48,
            noteName: 'C2',
            velocity: 115,
            probability: 1,
            offset: 0,
            accent: true,
            slide: true,
          },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          {
            enabled: true,
            pitch: 45,
            noteName: 'A1',
            velocity: 110,
            probability: 1,
            offset: 0,
            accent: false,
          },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          {
            enabled: true,
            pitch: 43,
            noteName: 'G1',
            velocity: 118,
            probability: 1,
            offset: 0,
            accent: true,
          },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          {
            enabled: true,
            pitch: 45,
            noteName: 'A1',
            velocity: 112,
            probability: 1,
            offset: 0,
            accent: false,
          },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          {
            enabled: true,
            pitch: 40,
            noteName: 'E1',
            velocity: 115,
            probability: 1,
            offset: 0,
            accent: true,
            slide: true,
          },
        ],
      },
      {
        id: 'ch-kick-amapiano',
        name: 'Amapiano Four-on-Floor Kick',
        sampleKey: 'kick',
        pitch: 36,
        volume: 0.92,
        pan: 0,
        muted: false,
        solo: false,
        steps: [
          { enabled: true, velocity: 115, probability: 1, offset: 0, accent: true },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 110, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 115, probability: 1, offset: 0, accent: true },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 110, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
        ],
      },
      {
        id: 'ch-shaker-amapiano',
        name: 'Swung Shaker Loop',
        sampleKey: 'shaker',
        pitch: 42,
        volume: 0.74,
        pan: 0.2,
        muted: false,
        solo: false,
        steps: Array.from({ length: 16 }, (_, i) => ({
          enabled: true,
          velocity: i % 2 === 1 ? 95 : 60,
          probability: 1,
          offset: 0.15,
          accent: i % 4 === 1,
        })),
      },
      {
        id: 'ch-clap-amapiano',
        name: 'Amapiano Soft Clap',
        sampleKey: 'clap',
        pitch: 39,
        volume: 0.85,
        pan: 0,
        muted: false,
        solo: false,
        steps: [
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 105, probability: 1, offset: 0, accent: true },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 105, probability: 1, offset: 0, accent: true },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
        ],
      },
    ],
  },

  // --------------------------------------------------------------------------
  // 5. PHONK: TOKYO PHONK DRIFT (130 BPM, E Minor)
  // --------------------------------------------------------------------------
  {
    id: 'loop-tokyo-phonk',
    name: 'Tokyo Phonk Drift 130',
    category: 'PHONK',
    bpm: 130,
    key: 'E Minor',
    description: 'Distorted 808 slides locked with phonk cowbell and heavy knocking kick drum.',
    eight08PresetId: '808-tokyo-phonk',
    channels: [
      {
        id: 'ch-808-phonk',
        name: 'SONIK Phonk Dirt 808',
        sampleKey: 'sonik_808',
        pitch: 40, // E1
        volume: 0.95,
        pan: 0,
        muted: false,
        solo: false,
        is808Channel: true,
        eight08Params: {
          mode: 'DIRTY',
          waveform: 'sub_distort',
          glideTime: 80,
          punchAttack: 0.88,
          decay: 2.2,
          drive: 0.82,
          subBoost: 6.5,
          legato: true,
        },
        steps: [
          {
            enabled: true,
            pitch: 40,
            noteName: 'E1',
            velocity: 120,
            probability: 1,
            offset: 0,
            accent: true,
          },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          {
            enabled: true,
            pitch: 40,
            noteName: 'E1',
            velocity: 105,
            probability: 1,
            offset: 0,
            accent: false,
          },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          {
            enabled: true,
            pitch: 43,
            noteName: 'G1',
            velocity: 115,
            probability: 1,
            offset: 0,
            accent: true,
          },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          {
            enabled: true,
            pitch: 38,
            noteName: 'D1',
            velocity: 110,
            probability: 1,
            offset: 0,
            accent: false,
          },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          {
            enabled: true,
            pitch: 40,
            noteName: 'E1',
            velocity: 112,
            probability: 1,
            offset: 0,
            accent: false,
          },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          {
            enabled: true,
            pitch: 52,
            noteName: 'E2',
            velocity: 118,
            probability: 1,
            offset: 0,
            accent: true,
            slide: true,
          },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
        ],
      },
      {
        id: 'ch-cowbell-phonk',
        name: 'Memphis Phonk Cowbell',
        sampleKey: 'cowbell',
        pitch: 68,
        volume: 0.85,
        pan: 0,
        muted: false,
        solo: false,
        steps: [
          { enabled: true, velocity: 110, probability: 1, offset: 0, accent: true },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 95, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 105, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 95, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 115, probability: 1, offset: 0, accent: true },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 95, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 105, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 110, probability: 1, offset: 0, accent: true },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
        ],
      },
      {
        id: 'ch-kick-phonk',
        name: 'Hard Memphis Kick',
        sampleKey: 'kick',
        pitch: 36,
        volume: 0.94,
        pan: 0,
        muted: false,
        solo: false,
        steps: [
          { enabled: true, velocity: 120, probability: 1, offset: 0, accent: true },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 105, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 118, probability: 1, offset: 0, accent: true },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 110, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
        ],
      },
      {
        id: 'ch-snare-phonk',
        name: 'Tight Phonk Snare',
        sampleKey: 'snare',
        pitch: 38,
        volume: 0.9,
        pan: 0,
        muted: false,
        solo: false,
        steps: [
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 115, probability: 1, offset: 0, accent: true },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 115, probability: 1, offset: 0, accent: true },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
        ],
      },
    ],
  },

  // --------------------------------------------------------------------------
  // 6. BOOM BAP: GOLDEN ERA CRUNCH (90 BPM, C Minor)
  // --------------------------------------------------------------------------
  {
    id: 'loop-boombap-punch',
    name: 'Boom Bap 90s Crunch 90',
    category: 'BOOM BAP',
    bpm: 90,
    key: 'C Minor',
    description:
      'Swung J Dilla groove with tight punchy 808 sub, crunchy rimshot, and organic ride cymbal.',
    eight08PresetId: '808-short-punch',
    channels: [
      {
        id: 'ch-808-boombap',
        name: 'SONIK Tight Punch 808',
        sampleKey: 'sonik_808',
        pitch: 36, // C1
        volume: 0.92,
        pan: 0,
        muted: false,
        solo: false,
        is808Channel: true,
        eight08Params: {
          mode: 'SHORT',
          waveform: 'sine',
          glideTime: 25,
          punchAttack: 0.95,
          decay: 0.9,
          drive: 0.32,
          subBoost: 4.0,
          legato: false,
        },
        steps: [
          {
            enabled: true,
            pitch: 36,
            noteName: 'C1',
            velocity: 115,
            probability: 1,
            offset: 0,
            accent: true,
          },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          {
            enabled: true,
            pitch: 36,
            noteName: 'C1',
            velocity: 90,
            probability: 1,
            offset: 0.08,
            accent: false,
          },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          {
            enabled: true,
            pitch: 39,
            noteName: 'D#1',
            velocity: 110,
            probability: 1,
            offset: 0,
            accent: true,
          },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          {
            enabled: true,
            pitch: 34,
            noteName: 'A#0',
            velocity: 105,
            probability: 1,
            offset: 0.06,
            accent: false,
          },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          {
            enabled: true,
            pitch: 36,
            noteName: 'C1',
            velocity: 95,
            probability: 1,
            offset: 0,
            accent: false,
          },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
        ],
      },
      {
        id: 'ch-kick-boombap',
        name: 'Vinyl Break Kick',
        sampleKey: 'kick',
        pitch: 36,
        volume: 0.9,
        pan: 0,
        muted: false,
        solo: false,
        steps: [
          { enabled: true, velocity: 120, probability: 1, offset: 0, accent: true },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 90, probability: 1, offset: 0.08, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 105, probability: 1, offset: 0.06, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
        ],
      },
      {
        id: 'ch-snare-boombap',
        name: 'Crunchy Snare & Rim',
        sampleKey: 'snare',
        pitch: 38,
        volume: 0.88,
        pan: 0,
        muted: false,
        solo: false,
        steps: [
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 115, probability: 1, offset: 0, accent: true },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: true, velocity: 115, probability: 1, offset: 0, accent: true },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
          { enabled: false, velocity: 100, probability: 1, offset: 0, accent: false },
        ],
      },
    ],
  },
];
