import { Track, VectorEmbeddingItem, N8nWorkflow } from '../types';

export const initialTracks: Track[] = [
  {
    id: 'track-3wm-001',
    title: 'Lagos Night Safari (Master Mix)',
    artist: 'Kappachino Emar x Kappachino Ricky ft. Kingpin',
    genre: 'Afrofusion / Amapiano Hybrid',
    bpm: 112,
    key: 'F# Minor',
    duration: 218,
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    status: 'mastered',
    settings: {
      volume: 0.92,
      pan: 0,
      eq: { low: 2.8, mid: -0.8, high: 2.2 },
      compression: { threshold: -18, ratio: 3.5, attack: 25, release: 120, makeupGain: 3.2 },
      reverb: { type: 'shrine', amount: 35, decay: 2.4 },
      mastering: {
        preset: 'Lagos Bounce',
        limiterCeiling: -0.3,
        targetLufs: -14.0,
        warmthSaturation: 68,
        stereoWidth: 118,
      },
    },
    analysis: {
      frequencies: {
        subBass: 8.4,
        bass: 9.1,
        lowMids: 6.8,
        mids: 7.2,
        highMids: 8.0,
        treble: 8.7,
        air: 7.9,
      },
      dynamics: {
        range: 8.2,
        rms: -13.6,
        peak: -0.3,
        lufs: -13.8,
      },
      afrobeatGrooveIndex: 94,
      harmonicWarmthScore: 89,
      suggestions: [
        'Sub-bass punch around 55Hz is sitting deep in the groove.',
        'High-hats have crisp polyrhythmic separation across the stereo field.',
        'BushBot recommends subtle 1.2dB high-shelf boost for shrine brass air.',
      ],
      agentInsights: {
        bushBot:
          'Solid Lagos bounce, brother! The conga snap and kick drum lock right into the pocket. Shrine reverb gives the vocal chant that legendary Kalakuta aura.',
        grok: 'Dynamic range is compressed to a competitive -13.8 LUFS. Frequency peaks at 4.2kHz are silky without harsh sibilance.',
        perplexity:
          'Automated Ozone Maximizer threshold dialed to -3.2dB with fast transient recovery. T-RackS tube saturation stage adds 4% harmonic warmth.',
      },
    },
    stems: [
      {
        id: 'stem-1',
        name: 'Vocals',
        volume: 0.95,
        pan: 0,
        muted: false,
        solo: false,
        color: '#f59e0b',
        waveformSeed: 12,
      },
      {
        id: 'stem-2',
        name: 'Drums & Percussion',
        volume: 0.9,
        pan: 0,
        muted: false,
        solo: false,
        color: '#ef4444',
        waveformSeed: 44,
      },
      {
        id: 'stem-3',
        name: 'Bassline',
        volume: 0.88,
        pan: 0,
        muted: false,
        solo: false,
        color: '#3b82f6',
        waveformSeed: 87,
      },
      {
        id: 'stem-4',
        name: 'Instruments & Horns',
        volume: 0.82,
        pan: -0.2,
        muted: false,
        solo: false,
        color: '#10b981',
        waveformSeed: 63,
      },
      {
        id: 'stem-5',
        name: 'FX & Synths',
        volume: 0.75,
        pan: 0.25,
        muted: false,
        solo: false,
        color: '#8b5cf6',
        waveformSeed: 29,
      },
    ],
    history: [
      {
        id: 'ev-1',
        timestamp: new Date(Date.now() - 7200000).toISOString(),
        agent: 'BushBot',
        action: 'Afrofusion Mixing',
        details: 'Dialed Lagos groove EQ & shrine reverb',
      },
      {
        id: 'ev-2',
        timestamp: new Date(Date.now() - 3600000).toISOString(),
        agent: 'Ozone 11',
        action: 'Mastering Chain',
        details: 'Applied Lagos Bounce preset with dynamic limiter',
      },
      {
        id: 'ev-3',
        timestamp: new Date(Date.now() - 1800000).toISOString(),
        agent: 'n8n AutoFlow',
        action: 'Boomplay Sync Ready',
        details: 'Master audio ready for high-fidelity export',
      },
    ],
  },
  {
    id: 'track-3wm-002',
    title: 'Eko Atlantic Vibe (Unmastered Stem)',
    artist: 'The Three Wise Men of Lagos',
    genre: 'Afro-Soul / Highlife Fusion',
    bpm: 104,
    key: 'A Minor',
    duration: 195,
    createdAt: new Date(Date.now() - 3600000 * 8).toISOString(),
    status: 'analyzing',
    settings: {
      volume: 0.85,
      pan: 0,
      eq: { low: 1.5, mid: 0.5, high: 1.0 },
      compression: { threshold: -14, ratio: 2.5, attack: 30, release: 150, makeupGain: 1.8 },
      reverb: { type: 'lagos_hall', amount: 25, decay: 1.8 },
      mastering: {
        preset: 'Afrofusion Warmth',
        limiterCeiling: -0.5,
        targetLufs: -14.0,
        warmthSaturation: 50,
        stereoWidth: 105,
      },
    },
    analysis: {
      frequencies: {
        subBass: 6.8,
        bass: 7.4,
        lowMids: 7.9,
        mids: 6.5,
        highMids: 6.2,
        treble: 7.0,
        air: 6.4,
      },
      dynamics: {
        range: 12.4,
        rms: -17.2,
        peak: -1.8,
        lufs: -18.2,
      },
      afrobeatGrooveIndex: 88,
      harmonicWarmthScore: 82,
      suggestions: [
        'Live saxophone stems need high-mid presence around 3.5kHz.',
        'Bass guitar has rich low-mid fundamentals, tighten below 40Hz with high-pass filter.',
        'Run Perplexity Mixin wizard to automate vintage tape glue compression.',
      ],
      agentInsights: {
        bushBot:
          'Smooth highlife horn phrasing here. Let us apply gentle opto-compression so the vocals glide right over the talking drums.',
        grok: 'Wide dynamic range (12.4 dB) ready for aggressive mastering limiter or subtle tape compression.',
        perplexity:
          'Suggested T-RackS automation: 2.8:1 ratio, 45ms attack, dual-stage warm tube drive.',
      },
    },
    stems: [
      {
        id: 'stem-1',
        name: 'Vocals',
        volume: 0.9,
        pan: 0,
        muted: false,
        solo: false,
        color: '#f59e0b',
        waveformSeed: 71,
      },
      {
        id: 'stem-2',
        name: 'Drums & Percussion',
        volume: 0.85,
        pan: 0,
        muted: false,
        solo: false,
        color: '#ef4444',
        waveformSeed: 19,
      },
      {
        id: 'stem-3',
        name: 'Bassline',
        volume: 0.8,
        pan: 0,
        muted: false,
        solo: false,
        color: '#3b82f6',
        waveformSeed: 55,
      },
      {
        id: 'stem-4',
        name: 'Instruments & Horns',
        volume: 0.88,
        pan: -0.15,
        muted: false,
        solo: false,
        color: '#10b981',
        waveformSeed: 38,
      },
      {
        id: 'stem-5',
        name: 'FX & Synths',
        volume: 0.7,
        pan: 0.2,
        muted: false,
        solo: false,
        color: '#8b5cf6',
        waveformSeed: 92,
      },
    ],
    history: [
      {
        id: 'ev-1',
        timestamp: new Date(Date.now() - 2800000).toISOString(),
        agent: 'Grok Audio',
        action: 'Spectral Analysis',
        details: 'Detected rich highlife acoustic profile',
      },
    ],
  },
];

export const vectorMemoryItems: VectorEmbeddingItem[] = [
  {
    id: 'vec-1',
    style: 'Classic Kalakuta Shrine Afrobeat',
    era: '1976-1985 Legacy Sound',
    acousticVector: [0.92, 0.78, 0.85, 0.65, 0.88, 0.95, 0.71, 0.84],
    referenceTracks: ['Zombie', 'Water No Get Enemy', 'Shakara'],
    signatureTraits: [
      'Analog Tape Warmth',
      'Shrine Plate Reverb',
      'Polyrhythmic Shekere transients',
      'Heavy tenor sax bite',
    ],
    provenance: {
      source: 'Kalakuta Archives 1977',
      timestamp: new Date().toISOString(),
      confidence: 0.98,
    },
  },
  {
    id: 'vec-2',
    style: 'Modern Lagos Afrofusion Bounce',
    era: '2023-Present Contemporary',
    acousticVector: [0.98, 0.94, 0.72, 0.89, 0.92, 0.83, 0.91, 0.96],
    referenceTracks: ['Lagos Night Safari', 'Afro-Futurism Anthem', 'Mainland Anthem'],
    signatureTraits: [
      'Log drum sub-bass 48Hz-62Hz',
      'Airy vocal doubles with subtle pitch correction',
      'Fast transient snare snaps',
      'Loudness target -13.5 LUFS',
    ],
    provenance: {
      source: '3WM Studio Vault',
      timestamp: new Date().toISOString(),
      confidence: 0.99,
    },
  },
  {
    id: 'vec-3',
    style: 'Palmwine Highlife & Juju Acoustic Space',
    era: 'Roots Fusion',
    acousticVector: [0.75, 0.69, 0.91, 0.58, 0.79, 0.82, 0.68, 0.77],
    referenceTracks: ['Sweet Mother Vibes', 'Island Juju Melody', 'Eko Atlantic Vibe'],
    signatureTraits: [
      'Natural room ambience',
      'Talking drum pitch glides',
      'Dual clean acoustic guitars',
      'Dynamic headroom preservation',
    ],
    provenance: {
      source: 'Lagos Heritage Audio Collection',
      timestamp: new Date().toISOString(),
      confidence: 0.95,
    },
  },
];

export const initialWorkflows: N8nWorkflow[] = [
  {
    id: 'wf-auto-mastering',
    name: 'Auto-Mastering Pipeline (Ozone 11 + T-RackS)',
    description:
      'Autonomous multi-stage audio normalization, dynamic EQ compensation, tape saturation, and loudness normalization to -14 LUFS.',
    status: 'idle',
    steps: [
      'Audio Normalization & DC Offset Removal',
      'Dynamic EQ & Afrobeat De-Essing',
      'Ozone 11 Lagos Bounce Maximizer',
      'Final WAV/FLAC 24-bit 48kHz Render',
    ],
  },
  {
    id: 'wf-boomplay-sync',
    name: 'Boomplay & Audiomack Direct Distribution',
    description:
      'Exports mastered audio, compiles ISRC/UPC metadata, generates waveform previews, and syncs directly to African streaming partners.',
    status: 'idle',
    steps: [
      'Metadata Verification (BPM, Key, ISRC)',
      'High-Resolution FLAC Encoding',
      'Boomplay Studio Portal API Sync',
      'Audiomack Streamer Trigger',
    ],
  },
  {
    id: 'wf-track-upload',
    name: 'Stem Separation & Spectral AI Ingestion',
    description:
      'Splits raw uploaded track into 5 isolated stems (Vocals, Drums, Bass, Horns, FX) and calculates acoustic vector embeddings.',
    status: 'idle',
    steps: [
      'Stem Decomposition AI',
      'Spectral Frequency Analysis',
      'Vector Memory Similarity Check',
      'BushBot Initial Mixing Recommendation',
    ],
  },
];
